# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazymake < Formula
  desc "A beautiful TUI for running Makefile targets"
  homepage "https://github.com/rshelekhov/lazymake"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.4.0/lazymake_0.4.0_Darwin_x86_64.tar.gz"
      sha256 "f524a293173b9239b1159e15bad45ed43736f0732babfe0bf6c4a01d7e0f1a81"

      def install
        bin.install "lazymake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.4.0/lazymake_0.4.0_Darwin_arm64.tar.gz"
      sha256 "0ff0842240a0f17584cd07d7652b804d544a5e313b8403130470fd9156fd2082"

      def install
        bin.install "lazymake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.4.0/lazymake_0.4.0_Linux_x86_64.tar.gz"
      sha256 "e8cc7ab04ba65a26bebada1f0b8e98528980b8e392aaa2ed3d17df0eeb71d852"
      def install
        bin.install "lazymake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.4.0/lazymake_0.4.0_Linux_arm64.tar.gz"
      sha256 "8acb71c3021a737fda61c2868e1c63975e10bb6f714f056fa7ff73c42d201619"
      def install
        bin.install "lazymake"
      end
    end
  end

  test do
    system "#{bin}/lazymake --version"
  end
end
