# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazymake < Formula
  desc "A beautiful TUI for running Makefile targets"
  homepage "https://github.com/rshelekhov/lazymake"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.1.0/lazymake_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "8b41701de9bf7a3dc0e0dbaf0a8c8a9376a6de2d92a7b1cf68768e6a56aa60ad"

      def install
        bin.install "lazymake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.1.0/lazymake_0.1.0_Darwin_arm64.tar.gz"
      sha256 "81a2ae8c503c36b707490e2e8d62a4e065f7857f69a487abdda216b46a7dd17f"

      def install
        bin.install "lazymake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.1.0/lazymake_0.1.0_Linux_x86_64.tar.gz"
      sha256 "1a85759d4b7d9c6f494a2819c940863acec0f6fa088561ff80b4f2acdde9c383"
      def install
        bin.install "lazymake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.1.0/lazymake_0.1.0_Linux_arm64.tar.gz"
      sha256 "c0749d0710b47287a5964ae1053bd65f92751e44aa2a128a4dfc9ae0db763277"
      def install
        bin.install "lazymake"
      end
    end
  end

  test do
    system "#{bin}/lazymake --version"
  end
end
