# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazymake < Formula
  desc "A beautiful TUI for running Makefile targets"
  homepage "https://github.com/rshelekhov/lazymake"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.3.0/lazymake_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "0f87f7fcaacdd113f2099befe96007fed0559a59e84feed90754d8cdbe4546b9"

      def install
        bin.install "lazymake"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.3.0/lazymake_0.3.0_Darwin_arm64.tar.gz"
      sha256 "dd54a07bd242862340108a1148c0890dab9ee634ad7acecdcf5ca95ff5ca3fef"

      def install
        bin.install "lazymake"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.3.0/lazymake_0.3.0_Linux_x86_64.tar.gz"
      sha256 "73c737bab372ce2dd93a3bcc0e69bef177033e473c2145d887b187c437f23264"
      def install
        bin.install "lazymake"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rshelekhov/lazymake/releases/download/v0.3.0/lazymake_0.3.0_Linux_arm64.tar.gz"
      sha256 "0a65bf7ebc388a02c7e0ee76d8356e7bae81e46a2a6177f5a1ec23b59031466c"
      def install
        bin.install "lazymake"
      end
    end
  end

  test do
    system "#{bin}/lazymake --version"
  end
end
